### ISSUE TITLE
Update Postman Collection

### ISSUE THREAD

**Issue by henry2man** [FIWARE/tutorials.Context-Providers#16]
I'm using the Postman Collections from the Step-by-step and, in this case, the postman collection in this repo is  more recent. The most obvious problem is that the published Postman collection still uses NGSI v1 queries.

The non-updated postman collection referred in the docs: https://app.getpostman.com/run-collection/7c9bed4bd2ce5213a80b

**Comment by MohamedSadiq102** [comment]
you should follow the Set up steps 
1) git clone git@github.com:FIWARE/tutorials.Context-Providers.git
2) cd tutorials.Context-Providers
3) ./services create; ./services start;
4) open Postman and start with Health Checks
